#!/bin/sh

# Set these paths appropriately

BIN=/home/etudiant/treetagger/bin
CMD=/home/etudiant/treetagger/cmd
LIB=/home/etudiant/treetagger/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/russian-utf8.par

# do tokenization
$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
