#!/bin/sh

# Set these paths appropriately

BIN=/home/etudiant/treetagger/bin
CMD=/home/etudiant/treetagger/cmd
LIB=/home/etudiant/treetagger/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/utf8-tokenize.perl
PARFILE=${LIB}/slovak-utf8.par

$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
