#!/bin/sh

# Set these paths appropriately

BIN=/home/touria/Bureau/ProjetM2Relation/projetTal-1.0.1/tree-tagger/bin
CMD=/home/touria/Bureau/ProjetM2Relation/projetTal-1.0.1/tree-tagger/cmd
LIB=/home/touria/Bureau/ProjetM2Relation/projetTal-1.0.1/tree-tagger/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/tokenize.pl
ABBR_LIST=${LIB}/swahili-abbreviations
PARFILE=${LIB}/swahili.par

$TOKENIZER -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
