#!/bin/sh

# Set these paths appropriately

BIN=/home/touria/Bureau/ProjetM2Relation/projetTal-1.0.1/tree-tagger/bin
CMD=/home/touria/Bureau/ProjetM2Relation/projetTal-1.0.1/tree-tagger/cmd
LIB=/home/touria/Bureau/ProjetM2Relation/projetTal-1.0.1/tree-tagger/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/french-abbreviations-utf8
PARFILE=${LIB}/french-utf8.par

$TOKENIZER -f -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
